title: Vehicle Classifier
description: Classify food images using deep learning
about:


  This is a Vehicle Images Classifier using Deep Learning built using Keras.



code: https://github.com/krishhrana/iitb_assignment